services:
  mariadb:
    env_file: .env
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - type: bind
        source: ./volume/mysql
        target: /var/lib/mysql
        bind:
          create_host_path: true
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 50
      test: [ "CMD", "pgrep", "mysqld" ]
    networks:
      - inception

  wordpress:
    env_file: .env
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - type: bind
        source: ./volume/var/www/html
        target: /var/www/html
        bind:
          create_host_path: true
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 50
      test: [ "CMD", "pgrep", "php-fpm7.4" ]
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

  nginx:
    env_file: .env
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - type: bind
        source: ./volume/var/www/html
        target: /var/www/html
        bind:
          create_host_path: true
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 50
      test: [ "CMD", "pgrep", "nginx" ]
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443
    networks:
      - inception


networks:
  inception:
    driver: bridge
