services:
  mariadb:
    env_file: .env
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - type: bind
        source: /home/arforgea/data/volume/mysql
        target: /var/lib/mysql
        bind:
          create_host_path: true
    restart: on-failure
    networks:
      - inception

  wordpress:
    env_file: .env
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - type: bind
        source: /home/arforgea/data/volume/var/www/html
        target: /var/www/html
        bind:
          create_host_path: true
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception

  nginx:
    env_file: .env
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - type: bind
        source: /home/arforgea/data/volume/var/www/html
        target: /var/www/html
        bind:
          create_host_path: true
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - 443:443
    networks:
      - inception


networks:
  inception:
    driver: bridge
